'use strict';
module.exports = {
  grant: {
    activity: { type: String },
    administeringIc: { type: String },
    applicationType: { type: Number },
    awardNoticeDate: { type: Date },
    budgetStart: { type: Date },
    budgetEnd: { type: Date },
    coreProjectNum: { type: String },
    edInstType: { type: String },
    fundingIcs: { type: Array },
    fundingMechanism: { type: String },
    fy: { type: Number },
    icName: { type: String },
    nihSpendingCats: { type: Array },
    orgCity: { type: String },
    orgCountry: { type: String },
    orgDept: { type: String },
    orgDistrict: { type: String },
    orgDuns: { type: String },
    orgFips: { type: String },
    orgName: { type: String },
    orgState: { type: String },
    orgZip: { type: String },
    phr: { type: String },
    piIds: { type: Array },
    piNames: { type: Array },
    programOfficerName: { type: String },
    projectStart: { type: Date },
    projectEnd: { type: Date },
    projectTerms: { type: Array },
    projectTitle: { type: String },
    studySection: { type: String },
    studySectionName: { type: String },
    supportYear: { type: Number },
    totalCost: { type: Number },
    activityType: { type: String },
    publications: { link: 'publication', inverse: 'grants', isArray: true }
  },

  publication: {
    affiliation: { type: String },
    authors: { type: String },
    country: { type: String },
    issn: { type: String },
    journalIssue: { type: String },
    journal: { type: String },
    journalAbbr: { type: String },
    journalVol: { type: String },
    lang: { type: String },
    page: { type: String },
    pmcId: { type: String },
    pubDate: { type: String },
    title: { type: String },
    pubYear: { type: String },
    grants: { link: 'grant', inverse: 'publications', isArray: true }
  }
};
