'use strict';
let schema = module.exports = {};

schema.grant = {
  activity: { type: String },
  administeringIc: { type: String },
  applicationType: { type: String },
  awardNoticeDate: { type: Date },
  budgetStart: { type: Date },
  budgetEnd: { type: Date },
  coreProjectNum: { type: String },
  edInstType: { type: String },
  fundingIcs: { type: String },
  fundingMechanism: { type: String },
  fy: { type: Number },
  icName: { type: String },
  nihSpendingCats: { type: String },
  orgCity: { type: String },
  orgCountry: { type: String },
  orgDept: { type: String },
  orgDistrict: { type: String },
  orgDuns: { type: String },
  orgFips: { type: String },
  orgName: { type: String },
  orgState: { type: String },
  orgZip: { type: String },
  phr: { type: String },
  piIds: { type: String },
  piNames: { type: String },
  programOfficerName: { type: String },
  projectStart: { type: Date },
  projectEnd: { type: Date },
  projectTerms: { type: String },
  projectTitle: { type: String },
  studySection: { type: String },
  studySectionName: { type: String },
  supportYear: { type: Number },
  totalCost: { type: Number },
  activityType: { type: String },
  publicationIds: { link: 'publication', inverse: 'projects', isArray: true }
};

schema.publication = {
  affiliation: { type: String },
  authors: { type: String },
  country: { type: String },
  issn: { type: String },
  journalIssue: { type: String },
  journal: { type: String },
  journalAbbr: { type: String },
  journalVol: { type: String },
  lang: { type: String },
  page: { type: String },
  pmcId: { type: String },
  pubDate: { type: String },
  title: { type: String },
  pubYear: { type: String },
  projects: { link: 'grant', inverse: 'publicationIds', isArray: true }
};
