---
sudo: required
language: node_js
node_js:
  - "4"
services:
  - mongodb
python:
  - "2.7"
cache:
  directories:
  - server/node_modules
  - client/node_modules
  - client/bower_components
before_install:
  # ETL
  - "mongo --eval 'db.runCommand({setParameter: 1, textSearchEnabled: true})' admin"
  - cd reporter-etl
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python="2.7" pymongo pandas xlrd
  - source activate test-environment
  - python buildDB.py install
  # Deps
  - npm install -g bower
  - npm install -g ember-cli
install:
  # Client build
  - cd ../client
  - npm install
  - bower install
  - npm install phantomjs-prebuilt
  # Server build
  - cd ../server
  - npm install
script:
  - cd ../client
  - npm rebuild node-sass
  - ember build --environment=production --output-path=../server/public
  #- npm test
