#---
#language: node_js
#node_js:
#  - "4"
#
#sudo: false
#
#cache:
#  directories:
#    - node_modules
#
#before_install:
#  - cd client
#  - npm config set spin false
#  - npm install -g bower
#  - bower --version
#  - npm install phantomjs-prebuilt
#  - phantomjs --version
#
#install:
#  - npm install
#  - bower install
#
#script:
#  - npm test

language: node_js
node_js:
  - "4"
services:
  - mongodb
cache:
  directories:
  - node_modules
before_install:
  - cd server
before_script:
  - npm prune
script:
  - npm test
