/**
 * Fixtures to be used for mongodb testing
 * 50 results generated by:
 *
 * db.getCollection('grant').aggregate([
 *   { $project : {
 *       projectTitle: 1 ,
 *       icName : 1,
 *       totalCost: 1,
 *       orgState: 1,
 *       awardNoticeDate: 1,
 *       activity: 1
 *     }
 *   }
 * ])
 *
 */

'use strict';
module.exports = {
    grants: [
        /* 1 */
        {
            '_id': 8835145,
            'projectTitle': 'Homeostatic Regulation of Supraoptic Neurons: Role of BDNF',
            'totalCost': 359525,
            'icName': 'NATIONAL HEART, LUNG, AND BLOOD INSTITUTE',
            'orgState': 'TX',
            'awardNoticeDate': new Date('2015-03-20T00:00:00.000Z'),
            'activity': 'R01'
        },

        /* 2 */
        {
            '_id': 9084781,
            'projectTitle': 'Molecular mechanisms of adult cortical plasticity',
            'totalCost': 423750,
            'icName': 'NATIONAL INSTITUTE OF NEUROLOGICAL DISORDERS AND STROKE',
            'orgState': 'NY',
            'awardNoticeDate': new Date('2015-07-17T00:00:00.000Z'),
            'activity': 'R56'
        },

        /* 3 */
        {
            '_id': 8811166,
            'projectTitle': 'Multidisciplinary NeuroAIDS Research Training to Improve HIV Outcomes in Nigeria',
            'totalCost': 276854,
            'icName': 'FOGARTY INTERNATIONAL CENTER',
            'orgState': 'IL',
            'awardNoticeDate': new Date('2015-01-24T00:00:00.000Z'),
            'activity': 'D43'
        },

        /* 4 */
        {
            '_id': 8987254,
            'projectTitle': 'Mechanisms of neuronal death during epileptogenesis',
            'totalCost': 427600,
            'icName': 'NATIONAL INSTITUTE OF NEUROLOGICAL DISORDERS AND STROKE',
            'orgState': 'MA',
            'awardNoticeDate': new Date('2015-07-28T00:00:00.000Z'),
            'activity': 'R37'
        },

        /* 5 */
        {
            '_id': 8808727,
            'projectTitle': 'Life Satisfaction Around the World',
            'totalCost': 568348,
            'icName': 'NATIONAL INSTITUTE ON AGING',
            'orgState': 'CA',
            'awardNoticeDate': new Date('2015-03-11T00:00:00.000Z'),
            'activity': 'R01'
        },

        /* 6 */
        {
            '_id': 8880084,
            'projectTitle': 'Study of Osteoporotic Fractures',
            'totalCost': 918027,
            'icName': 'NATIONAL INSTITUTE ON AGING',
            'orgState': 'CA',
            'awardNoticeDate': new Date('2015-05-07T00:00:00.000Z'),
            'activity': 'R01'
        },

        /* 7 */
        {
            '_id': 8795195,
            'projectTitle': 'University of Massachusetts IMSD',
            'totalCost': 471577,
            'icName': 'NATIONAL INSTITUTE OF GENERAL MEDICAL SCIENCES',
            'orgState': 'MA',
            'awardNoticeDate': new Date('2015-02-12T00:00:00.000Z'),
            'activity': 'R25'
        },

        /* 8 */
        {
            '_id': 8985298,
            'projectTitle': 'Small-Molecule Catalysts for the Stereoselective Synthesis of Oligosaccharides',
            'totalCost': 329690,
            'icName': 'NATIONAL INSTITUTE OF GENERAL MEDICAL SCIENCES',
            'orgState': 'MA',
            'awardNoticeDate': new Date('2015-07-09T00:00:00.000Z'),
            'activity': 'U01'
        },

        /* 9 */
        {
            '_id': 8832748,
            'projectTitle': 'Radiation Sterilizable Small Size RFID Tags for Biomedical Samples',
            'totalCost': 231757,
            'icName': 'OFFICE OF THE DIRECTOR, NATIONAL INSTITUTES OF HEALTH',
            'orgState': 'NJ',
            'awardNoticeDate': new Date('2015-03-16T00:00:00.000Z'),
            'activity': 'R43'
        },

        /* 10 */
        {
            '_id': 8904197,
            'projectTitle': 'Employing mouse models to translate early detection of pancreas cancer',
            'totalCost': 540000,
            'icName': 'NATIONAL CANCER INSTITUTE',
            'orgState': 'TX',
            'awardNoticeDate': new Date('2015-06-24T00:00:00.000Z'),
            'activity': 'R01'
        },

        /* 11 */
        {
            '_id': 8887723,
            'projectTitle': 'Trajectories of Nonmedical Prescription Drug Misuse',
            'totalCost': 232500,
            'icName': 'NATIONAL INSTITUTE ON DRUG ABUSE',
            'orgState': 'MI',
            'awardNoticeDate': new Date('2015-06-22T00:00:00.000Z'),
            'activity': 'R01'
        },

        /* 12 */
        {
            '_id': 8838745,
            'projectTitle': 'Bootstrap-based testing of rare sequence variants using family data',
            'totalCost': 325775,
            'icName': 'NATIONAL CANCER INSTITUTE',
            'orgState': 'CA',
            'awardNoticeDate': new Date('2015-04-22T00:00:00.000Z'),
            'activity': 'R01'
        },

        /* 13 */
        {
            '_id': 8850924,
            'projectTitle': 'Integrative mouse pathobiology: GI epithelial biology and genetics',
            'totalCost': 101627,
            'icName': 'OFFICE OF THE DIRECTOR, NATIONAL INSTITUTES OF HEALTH',
            'orgState': 'PA',
            'awardNoticeDate': new Date('2015-06-11T00:00:00.000Z'),
            'activity': 'K26'
        },

        /* 14 */
        {
            '_id': 8943715,
            'projectTitle': 'Nicotinic Acetylcholine Receptors and RV Dysfunction in Pulmonary Hypertension',
            'totalCost': 332026,
            'icName': 'NATIONAL HEART, LUNG, AND BLOOD INSTITUTE',
            'orgState': 'RI',
            'awardNoticeDate': new Date('2015-08-14T00:00:00.000Z'),
            'activity': 'R01'
        },

        /* 15 */
        {
            '_id': 8842056,
            'projectTitle': 'Biology of Aging and Age Related Diseases Training Grant',
            'totalCost': 439531,
            'icName': 'NATIONAL INSTITUTE ON AGING',
            'orgState': 'WI',
            'awardNoticeDate': new Date('2015-04-21T00:00:00.000Z'),
            'activity': 'T32'
        },

        /* 16 */
        {
            '_id': 8827708,
            'projectTitle': 'Integrating Anti-invasive and Anti-growth Therapies Targeting Cancer Metastasis',
            'totalCost': 325775,
            'icName': 'NATIONAL CANCER INSTITUTE',
            'orgState': 'NY',
            'awardNoticeDate': new Date('2015-05-01T00:00:00.000Z'),
            'activity': 'R01'
        },

        /* 17 */
        {
            '_id': 8829803,
            'projectTitle': 'low-dose and high-resolution tomosynthesis for lung cancer screening',
            'totalCost': 162536,
            'icName': 'NATIONAL CANCER INSTITUTE',
            'orgState': 'NC',
            'awardNoticeDate': new Date('2015-03-17T00:00:00.000Z'),
            'activity': 'R21'
        },

        /* 18 */
        {
            '_id': 8966489,
            'projectTitle': 'A FAST Assay to Quantify HIV Reservoirs',
            'totalCost': 606375,
            'icName': 'NATIONAL INSTITUTE OF ALLERGY AND INFECTIOUS DISEASES',
            'orgState': 'PA',
            'awardNoticeDate': new Date('2015-06-15T00:00:00.000Z'),
            'activity': 'R01'
        },

        /* 19 */
        {
            '_id': 8828317,
            'projectTitle': 'Short Term Training in Health Professional Schools',
            'totalCost': 46756,
            'icName': 'OFFICE OF THE DIRECTOR, NATIONAL INSTITUTES OF HEALTH',
            'orgState': 'KS',
            'awardNoticeDate': new Date('2015-04-02T00:00:00.000Z'),
            'activity': 'T35'
        },

        /* 20 */
        {
            '_id': 9054217,
            'projectTitle': 'Transcriptional regulation of oncogenic properties of mutant p53',
            'totalCost': 46499,
            'icName': 'NATIONAL CANCER INSTITUTE',
            'orgState': 'MS',
            'awardNoticeDate': new Date('2015-04-16T00:00:00.000Z'),
            'activity': 'R01'
        },

        /* 21 */
        {
            '_id': 8963925,
            'projectTitle': 'Multi-probe fluorescence imaging for rapid intra-operative tumor margin assessment',
            'totalCost': 556961,
            'icName': 'NATIONAL CANCER INSTITUTE',
            'orgState': 'NH',
            'awardNoticeDate': new Date('2015-07-06T00:00:00.000Z'),
            'activity': 'R01'
        },

        /* 22 */
        {
            '_id': 8852883,
            'projectTitle': 'Diabetes Prevention Program Outcomes Study Follow-up',
            'totalCost': 4852818,
            'icName': 'NATIONAL INSTITUTE OF DIABETES AND DIGESTIVE AND KIDNEY DISEASES',
            'orgState': 'DC',
            'awardNoticeDate': new Date('2015-01-30T00:00:00.000Z'),
            'activity': 'U01'
        },

        /* 23 */
        {
            '_id': 8928234,
            'projectTitle': 'Rett syndrome, MECP2 Duplications, and Rett-related Disorders Natural History',
            'totalCost': 1250000,
            'icName': 'EUNICE KENNEDY SHRIVER NATIONAL INSTITUTE OF CHILD HEALTH & HUMAN DEVELOPMENT',
            'orgState': 'AL',
            'awardNoticeDate': new Date('2015-08-31T00:00:00.000Z'),
            'activity': 'U54'
        },

        /* 24 */
        {
            '_id': 8841268,
            'projectTitle': 'CAT B Existing Wyoming PRAMS',
            'totalCost': 87450,
            'icName': 'NATIONAL CENTER FOR CHRONIC DISEASE PREV AND HEALTH PROMO',
            'orgState': 'WY',
            'awardNoticeDate': new Date('2015-04-17T00:00:00.000Z'),
            'activity': 'U01'
        },

        /* 25 */
        {
            '_id': 8828302,
            'projectTitle': 'Glutamate, brain connectivity and duration of untreated psychosis',
            'totalCost': 559356,
            'icName': 'NATIONAL INSTITUTE OF MENTAL HEALTH',
            'orgState': 'AL',
            'awardNoticeDate': new Date('2015-01-15T00:00:00.000Z'),
            'activity': 'R01'
        },

        /* 26 */
        {
            '_id': 8975838,
            'projectTitle': 'Multidisciplinary Training in Digestive Diseases',
            'totalCost': 57678,
            'icName': 'NATIONAL INSTITUTE OF DIABETES AND DIGESTIVE AND KIDNEY DISEASES',
            'orgState': 'MN',
            'awardNoticeDate': new Date('2015-01-16T00:00:00.000Z'),
            'activity': 'T32'
        },

        /* 27 */
        {
            '_id': 9115841,
            'projectTitle': 'The Outer Surface of Vibrio Cholerae',
            'totalCost': 399383,
            'icName': 'NATIONAL INSTITUTE OF ALLERGY AND INFECTIOUS DISEASES',
            'orgState': 'GA',
            'awardNoticeDate': new Date('2015-08-12T00:00:00.000Z'),
            'activity': 'R01'
        },

        /* 28 */
        {
            '_id': 9115016,
            'projectTitle': 'CCTN - CONTRACEPTIVE CLINICAL TRIALS NETWORK - CORE - FEMALE',
            'totalCost': 17620,
            'icName': 'EUNICE KENNEDY SHRIVER NATIONAL INSTITUTE OF CHILD HEALTH & HUMAN DEVELOPMENT',
            'orgState': 'VA',
            'awardNoticeDate': '',
            'activity': 'N01'
        },

        /* 29 */
        {
            '_id': 8799338,
            'projectTitle': 'ROLES OF SIALIDASE IN G. VAGINALIS-HOST INTERACTIONS DURING BACTERIAL VAGINOSIS',
            'totalCost': 619381,
            'icName': 'NATIONAL INSTITUTE OF ALLERGY AND INFECTIOUS DISEASES',
            'orgState': 'MO',
            'awardNoticeDate': new Date('2014-11-12T00:00:00.000Z'),
            'activity': 'R01'
        },

        /* 30 */
        {
            '_id': 8923237,
            'projectTitle': 'Autophagy-promoting NLRX1-TUFM complex and cancer cell resistance to cetuximab',
            'totalCost': 126792,
            'icName': 'NATIONAL INSTITUTE OF DENTAL & CRANIOFACIAL RESEARCH',
            'orgState': 'PA',
            'awardNoticeDate': new Date('2015-07-24T00:00:00.000Z'),
            'activity': 'K99'
        },

        /* 31 */
        {
            '_id': 9045208,
            'projectTitle': 'The Ohio State University Pancreatic Disorders Network (OSU-PDN)',
            'totalCost': 494029,
            'icName': 'NATIONAL INSTITUTE OF DIABETES AND DIGESTIVE AND KIDNEY DISEASES',
            'orgState': 'OH',
            'awardNoticeDate': new Date('2015-09-25T00:00:00.000Z'),
            'activity': 'U01'
        },

        /* 32 */
        {
            '_id': 8983038,
            'projectTitle': 'Exploring the effects of multi-iron site cooperativity and second sphere ligand interactions on NN bond cleavage in high-spin iron complexes',
            'totalCost': 36720,
            'icName': 'NATIONAL INSTITUTE OF GENERAL MEDICAL SCIENCES',
            'orgState': 'CT',
            'awardNoticeDate': new Date('2015-06-30T00:00:00.000Z'),
            'activity': 'F31'
        },

        /* 33 */
        {
            '_id': 8892261,
            'projectTitle': 'Action Monitoring and Genomic Variants in Pediatric Obsessive-Compulsive Behavior',
            'totalCost': 589944,
            'icName': 'NATIONAL INSTITUTE OF MENTAL HEALTH',
            'orgState': 'MI',
            'awardNoticeDate': new Date('2015-07-25T00:00:00.000Z'),
            'activity': 'R01'
        },

        /* 34 */
        {
            '_id': 9001397,
            'projectTitle': 'Unique Roles for Defined PVH Neurons in the Control of Energy Balance',
            'totalCost': 155500,
            'icName': 'NATIONAL INSTITUTE OF DIABETES AND DIGESTIVE AND KIDNEY DISEASES',
            'orgState': 'MI',
            'awardNoticeDate': new Date('2015-03-03T00:00:00.000Z'),
            'activity': 'R56'
        },

        /* 35 */
        {
            '_id': 8909660,
            'projectTitle': 'The role of endosomal adaptor proteins in cancer cell migration',
            'totalCost': 27480,
            'icName': 'NATIONAL CANCER INSTITUTE',
            'orgState': 'TN',
            'awardNoticeDate': new Date('2015-02-26T00:00:00.000Z'),
            'activity': 'F31'
        },

        /* 36 */
        {
            '_id': 8881178,
            'projectTitle': 'Environmental Biostatistics Training Grant',
            'totalCost': 146620,
            'icName': 'NATIONAL INSTITUTE OF ENVIRONMENTAL HEALTH SCIENCES',
            'orgState': 'GA',
            'awardNoticeDate': new Date('2015-06-30T00:00:00.000Z'),
            'activity': 'T32'
        },

        /* 37 */
        {
            '_id': 8906934,
            'projectTitle': 'Survival of the fittest HSPC repopulating clones by anti-HIV-1 gene-modification',
            'totalCost': 385000,
            'icName': 'NATIONAL HEART, LUNG, AND BLOOD INSTITUTE',
            'orgState': 'CA',
            'awardNoticeDate': new Date('2015-04-23T00:00:00.000Z'),
            'activity': 'R01'
        },

        /* 38 */
        {
            '_id': 8882079,
            'projectTitle': '1/5-COGNITIVE NEUROSCIENCE TASK RELIABILITY & CLINICAL APPLICATIONS CONSORTIUM',
            'totalCost': 306700,
            'icName': 'NATIONAL INSTITUTE OF MENTAL HEALTH',
            'orgState': 'MO',
            'awardNoticeDate': new Date('2015-06-09T00:00:00.000Z'),
            'activity': 'R01'
        },

        /* 39 */
        {
            '_id': 9143206,
            'projectTitle': 'Data Coordinating Center for Pilot Studies of Candidate Therapies for CKD',
            'totalCost': 300000,
            'icName': 'NATIONAL INSTITUTE OF DIABETES AND DIGESTIVE AND KIDNEY DISEASES',
            'orgState': 'OH',
            'awardNoticeDate': new Date('2015-09-14T00:00:00.000Z'),
            'activity': 'U01'
        },

        /* 40 */
        {
            '_id': 8818889,
            'projectTitle': 'GLYCOSYLATION MUTANTS OF LEISHMANIA',
            'totalCost': 614980,
            'icName': 'NATIONAL INSTITUTE OF ALLERGY AND INFECTIOUS DISEASES',
            'orgState': 'MO',
            'awardNoticeDate': new Date('2014-11-19T00:00:00.000Z'),
            'activity': 'R01'
        },

        /* 41 */
        {
            '_id': 9038905,
            'projectTitle': 'NYCDOHMH PPHF 2014 EPIDEMIOLOGY AND LABORATORY CAPACITY FOR INFECTIOUS DISEASES (ELC)',
            'totalCost': 2140307,
            'icName': 'CENTERS FOR DISEASE CONTROL AND PREVENTION',
            'orgState': 'NY',
            'awardNoticeDate': new Date('2015-03-24T00:00:00.000Z'),
            'activity': 'U50'
        },

        /* 42 */
        {
            '_id': 8786105,
            'projectTitle': 'Mechanisms of CaM Kinase II Signal Transduction',
            'totalCost': 493887,
            'icName': 'NATIONAL INSTITUTE OF MENTAL HEALTH',
            'orgState': 'TN',
            'awardNoticeDate': new Date('2014-12-11T00:00:00.000Z'),
            'activity': 'R01'
        },

        /* 43 */
        {
            '_id': 8823662,
            'projectTitle': 'Research Training in Gene-Environment Interaction in China',
            'totalCost': 220792,
            'icName': 'FOGARTY INTERNATIONAL CENTER',
            'orgState': 'LA',
            'awardNoticeDate': new Date('2015-03-12T00:00:00.000Z'),
            'activity': 'D43'
        },

        /* 44 */
        {
            '_id': 8902947,
            'projectTitle': 'Technology Assisted intervention for the Treatment and Prevention of Depression',
            'totalCost': 898993,
            'icName': 'NATIONAL INSTITUTE OF MENTAL HEALTH',
            'orgState': 'IL',
            'awardNoticeDate': new Date('2015-08-28T00:00:00.000Z'),
            'activity': 'P20'
        },

        /* 45 */
        {
            '_id': 9135611,
            'projectTitle': 'Continued studies of environment impact on puberty',
            'totalCost': 120892,
            'icName': 'NATIONAL INSTITUTE OF ENVIRONMENTAL HEALTH SCIENCES',
            'orgState': 'OH',
            'awardNoticeDate': new Date('2015-09-02T00:00:00.000Z'),
            'activity': 'U01'
        },

        /* 46 */
        {
            '_id': 9148287,
            'projectTitle': 'NYCDOHMH PPHF 2014 EPIDEMIOLOGY AND LABORATORY CAPACITY FOR INFECTIOUS DISEASES (ELC)',
            'totalCost': 1300000,
            'icName': 'CENTERS FOR DISEASE CONTROL AND PREVENTION',
            'orgState': 'NY',
            'awardNoticeDate': new Date('2015-09-23T00:00:00.000Z'),
            'activity': 'U50'
        },

        /* 47 */
        {
            '_id': 9000812,
            'projectTitle': 'PUERTO RICO POPULATION-BASED BIRTH DEFECTS SURVEILLANCE AND UTILIZATION OF SURVEI',
            'totalCost': 175000,
            'icName': 'National Center on Birth Defects and Developmental Disabilities',
            'orgState': 'PR',
            'awardNoticeDate': new Date('2015-03-10T00:00:00.000Z'),
            'activity': 'U50'
        },

        /* 48 */
        {
            '_id': 8852516,
            'projectTitle': 'Ambient Independence Measures for Guiding Care Transitions',
            'totalCost': 512253,
            'icName': 'NATIONAL INSTITUTE ON AGING',
            'orgState': 'OR',
            'awardNoticeDate': new Date('2015-02-27T00:00:00.000Z'),
            'activity': 'R01'
        },

        /* 49 */
        {
            '_id': 9041304,
            'projectTitle': 'Accelerated Bone Loss in Aging HIV-infected Individuals',
            'totalCost': 662266,
            'icName': 'NATIONAL INSTITUTE OF ARTHRITIS AND MUSCULOSKELETAL AND SKIN DISEASES',
            'orgState': 'GA',
            'awardNoticeDate': new Date('2015-09-18T00:00:00.000Z'),
            'activity': 'R01'
        },

        /* 50 */
        {
            '_id': 8607991,
            'projectTitle': 'Role of microRNAs in lipid metabolism and cardiovascular disease',
            'totalCost': 410006,
            'icName': 'NATIONAL HEART, LUNG, AND BLOOD INSTITUTE',
            'orgState': 'CT',
            'awardNoticeDate': new Date('2014-11-14T00:00:00.000Z'),
            'activity': 'R01'
        }
    ]  
};
