import Model from 'ember-data/model';
import attr from 'ember-data/attr';
export default Model.extend({
  activity: attr('string'),
  administeringIc: attr('string'),
  applicationType: attr('string'),
  awardNoticeDate: attr('string'),
  budgetStart: attr('string'),
  budgetEnd: attr('string'),
  edInstType: attr('string'),
  fundingIcs: attr('string'),
  fundingMechanism: attr('string'),
  fy: attr('string'),
  icName: attr('string'),
  nihSpendingCats: attr('string'),
  orgCity: attr('string'),
  orgCountry: attr('string'),
  orgDept: attr('string'),
  orgDistrict: attr('string'),
  orgDuns: attr('string'),
  orgFips: attr('string'),
  orgName: attr('string'),
  orgState: attr('string'),
  orgZip: attr('string'),
  phr: attr('string'),
  piNames: attr('string'),
  programOfficerName: attr('string'),
  projectStart: attr('string'),
  projectEnd: attr('string'),
  projectTerms: attr('string'),
  projectTitle: attr('string'),
  studySection: attr('string'),
  studySectionName: attr('string'),
  supportYear: attr('string'),
  directCostAmt: attr('string'),
  indirectCostAmt: attr('string'),
  totalCost: attr('string'),
  activityType: attr('string')
});
